# Copyright 2026 Loreum Digital Inc
# SPDX-License-Identifier: Apache-2.0
"""
WebSocket message classes
"""
from abc import ABC, abstractmethod
from typing import Optional, Dict, Any
from retiqo.crypto.ec_key import ECKey, ECDSASignature
from retiqo.crypto.hash_util import HashUtil
import base64


class Message(ABC):
    """Base class for WebSocket messages"""

    def __init__(self):
        """Initialize message"""
        import random
        self.signature: Optional[str] = None
        self.hash: Optional[str] = None
        # Random 16-bit nonce
        self.nonce: int = random.randint(0, 0xFFFF)

    @abstractmethod
    def get_verification_data(self) -> bytes:
        """Get data for signing/verification"""
        pass

    def sign(self, key: ECKey, message: Optional[bytes] = None) -> None:
        """Sign the message
        
        When called as sign(key), it internally calls sign(key, getVerificationData())
        over the message's verification data
        """
        import struct

        # Sign the verification data
        # So if message is None, we should use getVerificationData()
        if message is None:
            message = self.get_verification_data()
        
        # Nonce is encoded big-endian
        nonce_bytes = struct.pack(">I", self.nonce)  # Big-endian unsigned int

        # Hash is sha3(nonce) with no message, or sha3(message, nonce) otherwise
        # Since we set message = getVerificationData() if it was None, message should never be None here
        # For OpenChannelRequest, getVerificationData() returns nonce_bytes (new array)
        # So message = nonce_bytes (different reference from bb.array())
        # Here message is the nonce itself: sha3(nonce_bytes, nonce_bytes)
        # This concatenates both arrays
        if message is None:
            message_hash = HashUtil.sha3(nonce_bytes)
        else:
            # sha3(a, b) hashes a then b in one digest
            message_hash = HashUtil.sha3_multiple(message, nonce_bytes)

        ecdsa_signature = key.sign(message_hash)
        self.signature = ecdsa_signature.to_base64()
        self.hash = message_hash.hex()

    def verify(self, message: Optional[bytes] = None) -> ECKey:
        """Verify the message signature"""
        import struct

        verification_data = message if message is not None else self.get_verification_data()
        # Nonce is big-endian in the verification data
        nonce_bytes = struct.pack(">I", self.nonce)  # Big-endian unsigned int

        if message is None:
            message_hash = HashUtil.sha3(nonce_bytes)
        else:
            message_hash = HashUtil.sha3_multiple(message, nonce_bytes)

        if self.hash:
            supplied_hash = bytes.fromhex(self.hash)
            if message_hash != supplied_hash:
                raise ValueError("Signature verification failed: hash mismatch")

        # Key recovery would go here
        # For now, return None as placeholder
        return None


class Request(Message):
    """Base class for requests"""

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        result = {
            "nonce": self.nonce,
        }
        if self.signature:
            result["signature"] = self.signature
        if self.hash:
            result["hash"] = self.hash
        return result

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Request":
        """Create from dictionary"""
        instance = cls()
        instance.nonce = data.get("nonce", 0)
        instance.signature = data.get("signature")
        instance.hash = data.get("hash")
        return instance


class Result:
    """Base class for results"""

    def __init__(self, status: int = 0, description: str = "", channel_id: str = ""):
        """Initialize result"""
        self.status = status
        self.description = description
        self.channel_id = channel_id

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            "status": self.status,
            "description": self.description,
            "channelId": self.channel_id,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Result":
        """Create from dictionary"""
        return cls(
            status=data.get("status", 0),
            description=data.get("description", ""),
            channel_id=data.get("channelId", ""),
        )


class ProvisioningRequest(Request):
    """Provisioning request"""

    def __init__(self, app_id: str = "", device_id: str = "", device_address: Optional[str] = None):
        """Initialize provisioning request
        
        Args:
            app_id: Application ID
            device_id: Device ID
            device_address: Device's public key (address) - generated by device
        """
        super().__init__()
        self.type = "join"
        self.data = {"appid": app_id, "devid": device_id}
        if device_address:
            self.data["deviceaddress"] = device_address

    def get_verification_data(self) -> bytes:
        """Get verification data"""
        return b""  # Provisioning doesn't require signing

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        result = super().to_dict()
        result["type"] = self.type
        result["data"] = self.data
        return result


class ProvisioningResult(Result):
    """Provisioning result"""

    def __init__(self, status: int = 0, description: str = "", data: Optional[Dict[str, Any]] = None):
        """Initialize provisioning result"""
        super().__init__(status, description)
        self.data = data or {}

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ProvisioningResult":
        """Create from dictionary"""
        return cls(
            status=data.get("status", 0),
            description=data.get("description", ""),
            data=data.get("data", {}),
        )


class OpenChannelRequest(Request):
    """Open channel request"""

    def __init__(self, timeout: int = 120000, channel_id: str = ""):
        """Initialize open channel request"""
        super().__init__()
        self.type = "open"
        self.data = {
            "timeout": timeout,
            "channelid": channel_id  # Field names are lowercase on the wire
        }

    def get_verification_data(self) -> bytes:
        """Get verification data - returns nonce as 4 bytes (big-endian)"""
        # For OpenChannelRequest, verification data is the nonce as 4 bytes
        import struct
        return struct.pack(">I", self.nonce)  # Big-endian unsigned int
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        result = super().to_dict()
        result["type"] = self.type
        result["data"] = self.data
        return result


class OpenChannelResult(Result):
    """Open channel result"""

    def __init__(self, status: int = 0, description: str = "", data: Optional[Dict[str, Any]] = None):
        """Initialize open channel result"""
        super().__init__(status, description)
        self.data = data or {}

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "OpenChannelResult":
        """Create from dictionary"""
        return cls(
            status=data.get("status", 0),
            description=data.get("description", ""),
            data=data.get("data", {}),
        )


class CloseChannelRequest(Request):
    """Close channel request"""

    def __init__(self, channel_id: str):
        """Initialize close channel request"""
        super().__init__()
        self.type = "close"
        self.data = {"channelid": channel_id}  # Field names are lowercase on the wire

    def get_verification_data(self) -> bytes:
        """Get verification data"""
        return b""

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        result = super().to_dict()
        result["type"] = self.type
        result["data"] = self.data
        return result


class PayloadRequest(Request):
    """Payload request (for RTI method calls)"""

    def __init__(self, channel_id: str, payload: bytes):
        """Initialize payload request"""
        super().__init__()
        self.type = "payload"
        # Payload data is a hex string, not base64
        # The server expects hex encoding for the payload
        import binascii
        payload_hex = binascii.hexlify(payload).decode("utf-8")
        self.data = {
            "channelid": channel_id,  # Field names are lowercase on the wire
            "payload": payload_hex,  # Hex-encoded payload
        }

    def get_verification_data(self) -> bytes:
        """Get verification data - returns (payload.dataIn + channelId) as bytes"""
        # Verification data: payload hex followed by the channel ID
        # payload.dataIn is the hex string of the payload
        payload_hex = self.data.get("payload", "")
        channel_id = self.data.get("channelid") or self.data.get("channelId") or ""
        # Concatenate hex string payload and channel ID, then convert to bytes
        if not channel_id:
            raise ValueError(f"channel_id is None or empty in PayloadRequest. Data keys: {list(self.data.keys())}")
        verification_str = payload_hex + channel_id
        return verification_str.encode("utf-8")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        result = super().to_dict()
        result["type"] = self.type
        result["data"] = self.data
        return result


class PayloadResult(Result):
    """Payload result"""

    def __init__(self, status: int = 0, description: str = "", payload: Optional[bytes] = None):
        """Initialize payload result"""
        super().__init__(status, description)
        self.payload = payload

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "PayloadResult":
        """Create from dictionary"""
        payload_data = data.get("data", {}).get("payload")
        payload = None
        if payload_data:
            # Server sends Payload as an object with dataIn field (hex string)
            # or as a hex string directly
            if isinstance(payload_data, dict):
                # It's a Payload object: {"dataIn": "hex_string"}
                hex_str = payload_data.get("datain") or payload_data.get("dataIn")
                if hex_str:
                    import binascii
                    payload = binascii.unhexlify(hex_str)
            elif isinstance(payload_data, str):
                # It's a hex string directly
                import binascii
                try:
                    payload = binascii.unhexlify(payload_data)
                except (binascii.Error, ValueError):
                    # Try base64 as fallback
                    try:
                        payload = base64.b64decode(payload_data)
                    except Exception:
                        payload = None
        return cls(
            status=data.get("status", 0),
            description=data.get("description", ""),
            payload=payload,
        )


class KeepAliveRequest(Request):
    """Keep alive request"""

    def __init__(self):
        """Initialize keep alive request"""
        super().__init__()
        self.type = "keepalive"

    def get_verification_data(self) -> bytes:
        """Get verification data"""
        return b""

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        result = super().to_dict()
        result["type"] = self.type
        return result

